### PR TITLE
ENH: add support for XPD reciprocal space translation 

### PR DESCRIPTION
**Pull request by CJ-Wright**
from pixel position to Q, using pyFAI's calibration/geometry object, also PEP8

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@sameera2004 here is the pixel to Q function we were talking about today.

**Comment by tacaswell** [comment]
Can you make sure we have a conda rescipe for pyFai and add it as a dependancy in all of the correct places?

**Comment by CJ-Wright** [comment]
The conda recipe I am not sure about, never done that before.  But I will add pyFAI to the setup.py and travis.yml

**Comment by CJ-Wright** [comment]
@tacaswell are only conda packages allowed in meta.yaml?

**Comment by tacaswell** [comment]
Yes

**Comment by licode** [comment]
pyFAI is a good library to borrow. :+1:

**Comment by sameera2004** [comment]
@CJ-Wright sure thanks, yes it is good if we can use pyFAI for XPD data analysis

**Pull request merged**
