### PR TITLE
New save output

### PR DESCRIPTION
**Pull request by sameera2004**
Saving diffraction intensities into different file formats

### CODE REVIEW

**Comment by tacaswell** [comment]
```
import skxray.io.save_powder_output as spo
spo.save_output(range(5), range(5)[::-1], 'dummy', 'Q')
```

outputs:

```
 dummy
        This file contains integrated powder x-ray diffraction
        intensities.
        First column represents Q values (Angstroms) and second
        column represents intensities and if there is a third
        column it represents the error values of intensities.
        Number of data points in the file : 5
        ######################################################
        0.000000000000000000e+00 4.000000000000000000e+00
1.000000000000000000e+00 3.000000000000000000e+00
2.000000000000000000e+00 2.000000000000000000e+00
3.000000000000000000e+00 1.000000000000000000e+00
4.000000000000000000e+00 0.000000000000000000e+00

```
which does not look right to me.

**Comment by sameera2004** [comment]
@tacaswell I added a newline to fix that issue with the output file

**Comment by tacaswell** [comment]
This now outputs 

```
 dummy
        This file contains integrated powder x-ray diffraction
        intensities.
        First column represents Q values (Angstroms) and second
        column represents intensities and if there is a third
        column it represents the error values of intensities.
        Number of data points in the file : 5
        ######################################################
0.000000000000000000e+00 4.000000000000000000e+00
1.000000000000000000e+00 3.000000000000000000e+00
2.000000000000000000e+00 2.000000000000000000e+00
3.000000000000000000e+00 1.000000000000000000e+00
4.000000000000000000e+00 0.000000000000000000e+00
```

I is it supposed to have leading tabs on the header?

**Comment by sameera2004** [comment]
No, I just put it(the tab) in that way thinking it will easy to read.

**Comment by sameera2004** [comment]
I can even make it without the tab  too

**Comment by tacaswell** [comment]
I thought that these file formats had specifications, you should follow what ever that is.

**Comment by sameera2004** [comment]
They don't have specifications. If you take output files created by fit2d and SrXplanner it is totally differnt @tacaswell I will e-mail the files to you

**Pull request merged**
