### PR TITLE
ENH: Turn debug logger into a progressbar

### PR DESCRIPTION
**Pull request by ericdill**
- also add clint to the meta.yaml

### CODE REVIEW

**Comment by ericdill** [comment]
This PR adds a progress bar to the long running dpc code, as seen in the following screenshot
screenshot from 2015-07-17 12 16 53

**Comment by danielballan** [comment]
Neat. And, wheee more light useful dependencies! The README page for clint is hilarious.

**Comment by danielballan** [comment]
I assume Travis is cranky because clint needs to go in the .travis.yml.

**Comment by ericdill** [comment]
interesting note: clint is from the guy that maintains requests

**Comment by ericdill** [comment]
re offline conversation with @tacaswell , this progressbar thing should instead just be log-level messages. to do that properly, we should implement something like the logging PR that is currently against trackpy at soft-matter/trackpy#184

**Pull request closed without merging**
